services:
  - type: web
    name: financeApp
    env: java
    buildCommand: mvn install
    startCommand: java -jar target/financeApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.abcxyz.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: LEOgomes0605
